#!/usr/bin/env python3
"""Copy this repo's agentkit into each service's chat_agent/vendor/agentkit.

The service repos each deploy on their own, so they carry a copy of agentkit rather than a
path dependency on this directory. This repo stays the source of truth: edit agentkit here,
run the tests here, then sync.

    uv run scripts/sync_vendor.py            # copy upstream -> every vendor dir
    uv run scripts/sync_vendor.py --check    # report drift, change nothing (exit 1 if any)

Each vendor dir gets a VENDOR.json manifest of sha256 digests. `--check` compares upstream
against the copies. The service repos check their copy against its own manifest instead, with
vendor/check_vendor.py, which needs no access to this directory.
"""

import argparse
import hashlib
import json
import shutil
import sys
from pathlib import Path

KIT_ROOT = Path(__file__).resolve().parents[1]
SOURCE = KIT_ROOT / "src" / "agentkit"

# Relative to the ApiAgent directory that holds every repo.
TARGETS = (
    Path("ApiAgentService1") / "chat_agent" / "vendor" / "agentkit",
    Path("ApiAgentService2") / "chat_agent" / "vendor" / "agentkit",
)

CHECK_VENDOR = KIT_ROOT / "scripts" / "check_vendor.py"


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def source_files() -> dict[str, Path]:
    """Every agentkit source file, keyed by its path relative to src/agentkit."""
    return {
        str(path.relative_to(SOURCE)): path
        for path in sorted(SOURCE.rglob("*.py"))
        if "__pycache__" not in path.parts
    }


def vendor_pyproject() -> str:
    """The upstream pyproject, minus the parts a vendored copy has no use for.

    [project.scripts] stays: the chat agents are started with `uv run agentkit serve`. The dev
    group and pytest config go, because agentkit's tests are not vendored — they run upstream,
    before a sync. The readme goes too, since only the package source is copied.
    """
    text = (KIT_ROOT / "pyproject.toml").read_text()
    for section in ("[dependency-groups]", "[tool.pytest.ini_options]"):
        start = text.find(section)
        if start == -1:
            continue
        end = text.find("\n[", start + 1)
        text = text[:start] + (text[end + 1 :] if end != -1 else "")
    text = "".join(line for line in text.splitlines(keepends=True) if not line.startswith("readme ="))
    header = (
        "# Vendored from the ApiAgentKit repo by scripts/sync_vendor.py. Do not edit here:\n"
        "# change agentkit upstream and re-sync, or the next sync overwrites your change.\n"
    )
    return header + text.rstrip() + "\n"


def write_vendor(target: Path, files: dict[str, Path]) -> None:
    package = target / "src" / "agentkit"
    if package.exists():
        shutil.rmtree(package)
    for relative, path in files.items():
        destination = package / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(path, destination)

    (target / "pyproject.toml").write_text(vendor_pyproject())
    shutil.copy2(CHECK_VENDOR, target.parent / "check_vendor.py")

    manifest = {
        "source": "ApiAgentKit",
        "note": "Generated by ApiAgentKit/scripts/sync_vendor.py. Edit agentkit upstream, not here.",
        "files": {relative: digest(path) for relative, path in files.items()},
    }
    (target / "VENDOR.json").write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n")


def drift(target: Path, files: dict[str, Path]) -> list[str]:
    package = target / "src" / "agentkit"
    problems = []
    for relative, path in files.items():
        copy = package / relative
        if not copy.is_file():
            problems.append(f"missing: {relative}")
        elif digest(copy) != digest(path):
            problems.append(f"differs: {relative}")
    if package.exists():
        vendored = {
            str(path.relative_to(package))
            for path in package.rglob("*.py")
            if "__pycache__" not in path.parts
        }
        problems.extend(f"not upstream: {extra}" for extra in sorted(vendored - set(files)))
    return problems


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="report drift instead of copying")
    parser.add_argument(
        "--root",
        default=str(KIT_ROOT.parent),
        help="directory holding the service repos (default: the parent of this repo)",
    )
    args = parser.parse_args()

    root = Path(args.root).resolve()
    files = source_files()
    if not files:
        print(f"No agentkit sources under {SOURCE}", file=sys.stderr)
        return 1

    failed = False
    for relative in TARGETS:
        target = root / relative
        if not target.parent.parent.is_dir():
            print(f"skipped {relative}: {target.parent.parent} not found")
            continue

        if args.check:
            problems = drift(target, files)
            if problems:
                failed = True
                print(f"DRIFT {relative}")
                for problem in problems:
                    print(f"  {problem}")
            else:
                print(f"ok    {relative} ({len(files)} files)")
        else:
            write_vendor(target, files)
            print(f"synced {relative} ({len(files)} files)")

    if failed:
        print("\nRun without --check to overwrite the copies from upstream.", file=sys.stderr)
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
